name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  version-and-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    outputs:
      new_version: ${{ steps.semantic.outputs.new_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/github @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec conventional-changelog-conventionalcommits

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESULT=$(npx semantic-release)
          VERSION=$(echo "$RESULT" | grep -oP "Published release \K[0-9]+\.[0-9]+\.[0-9]+" || echo "")
          if [ ! -z "$VERSION" ]; then
            echo "new_version=$VERSION" >> $GITHUB_OUTPUT
            echo "new_release_published=true" >> $GITHUB_OUTPUT
          else
            echo "new_version=" >> $GITHUB_OUTPUT
            echo "new_release_published=false" >> $GITHUB_OUTPUT
          fi

      - name: Verify Release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "New version released: ${{ steps.semantic.outputs.new_version }}"
          echo "VERSION file content: $(cat VERSION)"

      - name: Debug Semantic Release Outputs
        run: |
          echo "New version: ${{ steps.semantic.outputs.new_version }}"
          echo "Release published: ${{ steps.semantic.outputs.new_release_published }}"

  build-and-push:
    needs: version-and-release
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.version-and-release.outputs.new_release_published == 'true') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-24.04
    steps:
      - name: Debug Job Conditions
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "New version: ${{ needs.version-and-release.outputs.new_version }}"
          echo "Release published: ${{ needs.version-and-release.outputs.new_release_published }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
          buildkitd-flags: --debug

      - name: Log in to Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=${{ needs.version-and-release.outputs.new_version }},enable=${{ needs.version-and-release.outputs.new_version != '' }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ needs.version-and-release.outputs.new_version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            VERSION=${{ needs.version-and-release.outputs.new_version || 'dev' }}
          provenance: false

      - name: Set fallback version
        if: needs.version-and-release.outputs.new_version == ''
        run: |
          echo "No new version, using fallback"
          echo "new_version=dev" >> $GITHUB_ENV 